INDIAN_AIRPORTS = [
    {"iata_code": "DEL", "name": "Indira Gandhi International Airport", "city": "New Delhi"},
    {"iata_code": "BOM", "name": "Chhatrapati Shivaji Maharaj International Airport", "city": "Mumbai"},
    {"iata_code": "BLR", "name": "Kempegowda International Airport", "city": "Bangalore"},
    {"iata_code": "MAA", "name": "Chennai International Airport", "city": "Chennai"},
    {"iata_code": "HYD", "name": "Rajiv Gandhi International Airport", "city": "Hyderabad"},
    {"iata_code": "CCU", "name": "Netaji Subhas Chandra Bose International Airport", "city": "Kolkata"},
    {"iata_code": "GOI", "name": "Goa International Airport", "city": "Goa"},
    {"iata_code": "PNQ", "name": "Pune Airport", "city": "Pune"},
    {"iata_code": "COK", "name": "Cochin International Airport", "city": "Kochi"},
    {"iata_code": "AMD", "name": "Sardar Vallabhbhai Patel International Airport", "city": "Ahmedabad"},
    {"iata_code": "IXC", "name": "Chandigarh Airport", "city": "Chandigarh"},
    {"iata_code": "LKO", "name": "Chaudhary Charan Singh International Airport", "city": "Lucknow"},
    {"iata_code": "TRV", "name": "Trivandrum International Airport", "city": "Thiruvananthapuram"},
    {"iata_code": "JAI", "name": "Jaipur International Airport", "city": "Jaipur"},
    {"iata_code": "PAT", "name": "Lok Nayak Jayaprakash Airport", "city": "Patna"},
    {"iata_code": "VNS", "name": "Lal Bahadur Shastri Airport", "city": "Varanasi"},
    {"iata_code": "IXB", "name": "Bagdogra Airport", "city": "Siliguri"},
    {"iata_code": "SXR", "name": "Sheikh-ul-Alam International Airport", "city": "Srinagar"},
    {"iata_code": "GAU", "name": "Lokpriya Gopinath Bordoloi International Airport", "city": "Guwahati"},
    {"iata_code": "IXR", "name": "Birsa Munda Airport", "city": "Ranchi"},
    {"iata_code": "RPR", "name": "Swami Vivekananda Airport", "city": "Raipur"},
    {"iata_code": "NAG", "name": "Dr. Babasaheb Ambedkar International Airport", "city": "Nagpur"},
    {"iata_code": "IXE", "name": "Mangalore International Airport", "city": "Mangalore"},
    {"iata_code": "BHU", "name": "Bhubaneswar Airport", "city": "Bhubaneswar"},
    {"iata_code": "IDR", "name": "Devi Ahilya Bai Holkar Airport", "city": "Indore"},
    {"iata_code": "UDR", "name": "Maharana Pratap Airport", "city": "Udaipur"},
    {"iata_code": "IXJ", "name": "Jammu Airport", "city": "Jammu"},
    {"iata_code": "IXS", "name": "Silchar Airport", "city": "Silchar"},
    {"iata_code": "TRZ", "name": "Tiruchirappalli International Airport", "city": "Tiruchirappalli"},
    {"iata_code": "IXM", "name": "Madurai Airport", "city": "Madurai"},
    {"iata_code": "IXY", "name": "Kozhikode International Airport", "city": "Kozhikode"},
    {"iata_code": "BHJ", "name": "Bhuj Airport", "city": "Bhuj"},
    {"iata_code": "LUD", "name": "Chandigarh Airport", "city": "Ludhiana"}
]
